### ISSUE TITLE
Add token test in integration test

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/boxd#165]
1. Issue a token

`./box --log-level debug --wallet_dir keyfile token issue b1YVxYU6ANzJ7GNpM2Utv67zDVAidd63fJ1 b1YVxYU6ANzJ7GNpM2Utv67zDVAidd63fJ1 box 100`

2. Get the token issue tx id from console output and set it for later use

`txid=a44c2f5570cbc741d83e2cd812af772b2b84df96748b48e07c489a2b4b3222b6`

3. Check balance: expect 100. Note: you have to wait for the tx to be mined into a block for the balance to be reflected.
`./box --wallet_dir keyfile --log-level debug token getbalance b1ZF5VWYdHv5RrRzP3SD5huGFyqWNq8rquJ $txid 0`

4. Transfer 40 tokens.
`./box --log-level debug token --wallet_dir keyfile transfer b1YVxYU6ANzJ7GNpM2Utv67zDVAidd63fJ1 $txid 0 b1ZF5VWYdHv5RrRzP3SD5huGFyqWNq8rquJ 40`

5. The sender should have 60 tokens left. The receiver 40 tokens.
```
./box --wallet_dir keyfile --log-level debug token getbalance b1YVxYU6ANzJ7GNpM2Utv67zDVAidd63fJ1 $txid 0
./box --wallet_dir keyfile --log-level debug token getbalance b1ZF5VWYdHv5RrRzP3SD5huGFyqWNq8rquJ $txid 0
```

**Comment by Jerick26** [comment]
done
