### ISSUE TITLE
Errors in integration test

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/boxd#186]
[Test still passes in spite of two errors](https://travis-ci.com/BOXFoundation/boxd/builds/91724080). Is this expected?
```
ERRO[0074] Failed to verify miner epoch. Hash: 65294ded1f8d914d8994721d4cd2ff78067c9ac45081f8199e18591c94dcd213, Height: 12, Err: Invalid miner epoch  source="chain/blockchain.go:313" tag=chain
ERRO[0104] Failed to accept the block into the main chain. Err: Failed to verify block with consensus  source="chain/blockchain.go:262" tag=chain
```

`ERRO[0106] ReadMessage occurs error. Err: stream reset   source="p2p/conn.go:92" tag=p2p`

**Comment by Jerick26** [comment]
Now I cannot reproduce it locally. We reopen it when it occurs again.
