### ISSUE TITLE
Network partition test in CI

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/boxd#192]
Partition the network into two parts, e.g., change from testnet to mainnet, and then merge them, and ensure they are back to normal.

Make a boolean flag in integration test to only run this kind of heavy operation when the flag is set.

**Comment by Jerick26** [comment]
finish on 29482e693426ad2a835eff4ae9656d8796b3b2b4

**Comment by Jerick26** [comment]
usage:
    - http --json http://127.0.0.1:19190/v1/ctl/networkid id=1234
    - ./box ctl networkid 1234

**Comment by Jerick26** [comment]
testnet: 1413829460
