### ISSUE TITLE
CI broken: dial attempt failed: connection refused

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/boxd#212]
[Build#186](https://travis-ci.com/BOXFoundation/boxd/builds/93017046) and [Build187](https://travis-ci.com/BOXFoundation/boxd/builds/93083595). Reproducible with same error on my local machine.
`./integration_tests -nodes=true`

**Comment by Jerick26** [comment]
I come across it on my local too.
I guess it is caused by last execution dirty exit.

**Comment by Jerick26** [comment]
It is caused by nodes lately starting that normal nodes start before the seed node.
It is not a problem!
