### ISSUE TITLE
Why are there so many txs in our tx_pool that can't be packaged?

### ISSUE THREAD

**Issue by LeonLi000** [BOXFoundation/boxd#218]
![image](https://user-images.githubusercontent.com/6380914/49441001-36ed2600-f800-11e8-8a96-78d72ec913d8.png)

**Comment by xhliu** [comment]
Let's talk more after the meeting.

**Comment by xhliu** [comment]
Discussed with @LeonLi000 , who's going to investigate.

**Comment by xujingshi** [comment]
Steps to reproduce the issue(boxd001):
1. `cd /home/app/pzg/boxd/integration_tests`
2. `./integration_tests --nodes=false --scope=continue` for 3 times. Maybe 1 process is enough, but I opened 3.
3. Wait a few minutes and close the integration tests. You will find the problem. @xhliu

**Comment by xujingshi** [comment]
Steps to rebuild:
1. Supervisord config path: /etc/supervisor/conf.d, and you will find all boxd process are based on command `/box/app/box start --config=box.yaml`
2. You can modify the code and make it in /box/app/boxd
3. Then `sudo cp /box/app/boxd/box /box/app/box`
4. `sudo supervisorctl restart all`
