### ISSUE TITLE
Bug report template

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/boxd#224]
Can we use the following format when reporting bugs? Most bugs are currently reported as simply reporting the error message, with which it's often hard to debug and fix. By providing a standard way to report them and giving as much info as possible, we can speed up debugging and all benefit. Let me know if you have any suggestions/comments.

#### Steps to reproduce the issue

1.  
2. 
3. 

#### What's the expected and actual result?

-

#### What has been done to try to fix this issue?

-

#### Additional details

**Comment by jiaruijiang** [comment]
bug report issue template added
