### ISSUE TITLE
tx pool size increase rapidly

### ISSUE THREAD

**Issue by Jerick26** [BOXFoundation/boxd#245]
## Steps to Reproduce

1. stress test param:
  "transaction_test": {
    "enable": true,
    "collection_accounts": 12,
    "collection_unit_accounts": 4,
    "circulation_accounts": 9,
    "circulation_unit_accounts": 3,
    "circulation_repeat_times": 800
  },
2. commit Id: c761e12d09b9dacaf7a5f6527c65cd3f394b591a
3.
4.

## Detailed Description

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/23067882/50548834-67ed3900-0c8e-11e9-9e08-edcfb85317a1.png">

**Comment by xhliu** [comment]
@Jerick26 Can we close this if it's no longer an issue?

**Comment by Jerick26** [comment]
okay.
Now it appears no longer.
commit id: 073e049219a56f0dd5fdd9977e7afd55b7d5d33b
