### ISSUE TITLE
There are many orphan txs in pool after 3days stress test

### ISSUE THREAD

**Issue by Jerick26** [BOXFoundation/boxd#246]
## Expected Behavior

No orphan txs in pool

## Current Behavior

There are about 25K orphan txs in pool of miner nodes and wallet nodes.

## Steps to Reproduce

1. nodes run about 3 days in test-net and in stress test

## Context (Environment)

commit: c761e12d09b9dacaf7a5f6527c65cd3f394b591a

## Detailed Description

![wechatworkscreenshot_565dd15a-7b35-421e-b2e3-569d1566d9ab](https://user-images.githubusercontent.com/23067882/50580376-c5e57080-0e88-11e9-978b-b43cf4af04ce.png)

**Comment by xhliu** [comment]
@Jerick26 @LeonLi000 This can be closed?

**Comment by Jerick26** [comment]
yes.
resolve commit: 073e049219a56f0dd5fdd9977e7afd55b7d5d33b
