### ISSUE TITLE
integration_tests build failure

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/boxd#267]
# github.com/BOXFoundation/boxd/integration_tests [github.com/BOXFoundation/boxd/integration_tests.test]
integration_tests/wallet_plugin_test.go:75:18: acc.Sign undefined (type interface {} is interface with no methods)
integration_tests/wallet_plugin_test.go:79:47: acc.PublicKey undefined (type interface {} is interface with no methods)
ok  	github.com/BOXFoundation/boxd/core/chain	7.775s
?   	github.com/BOXFoundation/boxd/core/metrics	[no test files]
?   	github.com/BOXFoundation/boxd/core/pb	[no test files]
ok  	github.com/BOXFoundation/boxd/core/txlogic	0.044s
ok  	github.com/BOXFoundation/boxd/core/txpool	0.077s
ok  	github.com/BOXFoundation/boxd/core/types	0.042s
ok  	github.com/BOXFoundation/boxd/crypto	0.061s
FAIL	github.com/BOXFoundation/boxd/integration_tests [build failed]

**Comment by Jerick26** [comment]
fixed after merging branch rpc_refine
