### ISSUE TITLE
Split addresses are same in different txs

### ISSUE THREAD

**Issue by wangjunbao2018** [BOXFoundation/boxd#273]
In the case,  A user create different transactions, and create split addresses,  they have the same spit address.

## Expected Behavior
The split addresses should not be the same.

## Current Behavior
The split addresses are the same.

## Steps to Reproduce

To reproduce the case, just use these two transactions and analyze the result:

- c42de808621cd21bfaec180fb34b9862060f185e1b70abc287bb3ad34c04be70
- c42de808621cd21bfaec180fb34b9862060f185e1b70abc287bb3ad34c04be70

The split address is **b2Zh9oN4Ns1LtkYUdMcrQuQgXotsTtvSeTh**

For more details,  run the  cli below:

```
echo '{"hash":"c42de808621cd21bfaec180fb34b9862060f185e1b70abc287bb3ad34c04be70"}' | http POST http://39.97.169.1:19110/v1/tx/detail
```

```
echo '{"hash":"ae58fdbd80aa0eb2b11a391f08d53b05b3be9f3d9f689a42bb67a85ca77e5d32"}' | http POST http://39.97.169.1:19110/v1/tx/detail
```

**Comment by Jerick26** [comment]
Because split address is only a address, that is not relevant with transaction. The information in split address is the addresses and weights that every address take.
