### ISSUE TITLE
"no contract code at given address" when calling a contract method

### ISSUE THREAD

**Issue by xhliu** [BOXFoundation/boxd#294]
A contract is deployed at `b5h8ZdV7cuNQxrKeSxvRCdEFMxRT4xUmeuH`, but

![image](https://user-images.githubusercontent.com/1017252/59571382-d82f2180-9058-11e9-88b7-04c3816183a1.png)

Ignore data field bcoz the same error shows up when it is properly populated.

**Comment by Jerick26** [comment]
fixed.
