### ISSUE TITLE
viewTxDetail  returns "EOF"

### ISSUE THREAD

**Issue by wangjunbao2018** [BOXFoundation/boxd#297]
After I deployed a contract,  I tried to check the transaction, I got the error return.

```
code: -1
message: "EOF"
```

## Steps to Reproduce

1.
2.
3.
4.

**Comment by xhliu** [comment]
Javascript API has the same error.

**Comment by Jerick26** [comment]
This issue occurred because of this tx not brought on chain yet.
If to wait more time before calling ViewTxDetail rpc api the wrong response maybe disappear.
